PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizza_app.urls'))
]

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizza_app/urls.py
from django.urls import path

from . import views

app_name = 'pizza_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza')
]

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizza_app/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    text = models.TextField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizza_app/views.py
from django.shortcuts import render
from .models import Pizza

# Create your views here.
def index(request):
    return render(request, 'pizza_app/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizza_app/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizza_app/pizza.html', context)

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizzas/views.py
from django.shortcuts import render

# Create your views here.

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizza_app/templates/pizza_app/base.html
<p>
    <a href="{% url 'pizza_app:index' %}">Pizzaria</a>-<a href="{% url 'pizza_app:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %} 

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizza_app/templates/pizza_app/index.html
{% extends "pizza_app/base.html" %} 

    {% block content %} 
    <p>Finding what you love!</p>
    {% endblock content %} 

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizza_app/templates/pizza_app/pizza.html
{% extends 'pizza_app/base.html' %} 

{% block content %} 
    <p>Pizza: {{ pizza }}</p>

    <p>Topping:</p>
    <ul>
        {% for topping in toppings %} 
        <li>
            <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ topping.text|linebreaks }}</p>
        </li>
        {% empty %}
        <li>There are no entries for this pizza yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}

PythonStudy/pythonProgrammingFromIntro2Practice/Pizzeria/pizza_app/templates/pizza_app/pizzas.html
{% extends "pizza_app/base.html" %} 
{% block content %} 

    <p>Pizzas</p>

    <ul>
        {% for pizza in pizzas %} 
            <li>
                <a href="{% url 'pizza_app:pizza' pizza.id %}">{{ pizza }}</a>
            </li>
        {% empty %} 
            <li>No pizzas have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %} 